# -*- coding: utf-8 -*-
"""Single cell RNA sequencing- HackBio Stage Two

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntZ0rkGtKN57eOzHXYFhzuhaAMhk_7K7

HackBio Stage Two

Reproduce a single-cell analysis pipleine using Scanpy and Anndata
Dataset is BoneMarrow.h5ad.

INSTALLATION OF TOOLS:
Scanpy
Anndata
igraph
Celltypist
Decoupler
"""

!pip install scanpy
!pip install anndata
!pip install igraph
!pip install celltypist
!pip install decoupler

"""LOADING OF DATA"""

# import core tools
import scanpy as sc
import anndata as ad

!wget https://media.githubusercontent.com/media/josoga2/sc/refs/heads/main/bone_marrow.h5ad

bone_marrow_adata = sc.read('bone_marrow.h5ad')

print(bone_marrow_adata)

bone_marrow_adata.shape

bone_marrow_adata.var.head()

bone_marrow_adata.obs.head()

# Assign to DataFrame
bone_marrow_adata.to_df()

"""QUALITY CONTROL: To keep high quality cells and informative genes"""

# Quality control of genes and cells
bone_marrow_adata.var_names_make_unique()
bone_marrow_adata.obs_names_make_unique()

bone_marrow_adata.var['MT'] = bone_marrow_adata.var['feature_name'].str.startswith('MT-')
bone_marrow_adata.var['RIBO'] = bone_marrow_adata.var['feature_name'].str.startswith(('RPS', 'RPL'))
bone_marrow_adata.var['HB'] = bone_marrow_adata.var['feature_name'].str.contains('^HB[^(P)]', regex=True)

mt_genes = bone_marrow_adata.var[bone_marrow_adata.var['MT']]
mt_genes

sc.pp.calculate_qc_metrics(
bone_marrow_adata, qc_vars=["MT", 'RIBO', 'HB'], inplace=True, log1p=True
)

bone_marrow_adata.obs.head()

bone_marrow_adata.var.head()

# number of genes in cells
sc.pl.violin(
    bone_marrow_adata,
    ["n_genes_by_counts"],
    jitter=0.4,
    multi_panel=False,
)

# Total counts of genes
sc.pl.violin(
    bone_marrow_adata,
    ["total_counts"],
    jitter=0.4,
    multi_panel=False,
)

# Mitochondrial genes
sc.pl.violin(
    bone_marrow_adata,
    ["pct_counts_MT"],
    jitter=0.4,
    multi_panel=False,
)

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_HB")

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_RIBO")

bone_marrow_adata = bone_marrow_adata[
    bone_marrow_adata.obs['pct_counts_RIBO'] < 10,
    :
]

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color = "pct_counts_RIBO")

# Filtration of cells and genes
sc.pp.filter_cells(bone_marrow_adata, min_genes=1000)
sc.pp.filter_genes(bone_marrow_adata, min_cells=1000)

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

sc.pp.scrublet(bone_marrow_adata) #doublet detection

"""NORMALIZATION"""

bone_marrow_adata.layers["counts"] = bone_marrow_adata.X.copy()

# Normalizing to median total counts
sc.pp.normalize_total(bone_marrow_adata)
# Logarithmize the data
sc.pp.log1p(bone_marrow_adata)

sc.pp.highly_variable_genes(bone_marrow_adata)

sc.pl.highly_variable_genes(bone_marrow_adata )

"""Dimensionality Reduction: Principal Component Analysis, UMAP. Non Linear Dimensionality Reduction: Leiden"""

# Principal Component Analysis
sc.tl.pca(bone_marrow_adata)

sc.pl.pca_variance_ratio(bone_marrow_adata, n_pcs=10, log=False)

sc.pp.neighbors(bone_marrow_adata)

sc.tl.umap(bone_marrow_adata)

sc.pl.pca(
    bone_marrow_adata,
    color=["pct_counts_MT"]
)

sc.pl.pca(
    bone_marrow_adata,
    color=["pct_counts_HB"]
)

sc.pp.neighbors(bone_marrow_adata)

sc.tl.umap(bone_marrow_adata)

sc.pl.umap(
    bone_marrow_adata,
    color=["pct_counts_RIBO"],
    size=8,
)

sc.pl.umap(
    bone_marrow_adata,
    color=["pct_counts_HB"],
    size=8,
)

sc.pl.umap(
    bone_marrow_adata,
    color=["pct_counts_MT"],
    size=8,
)

sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2)

# Cell clustering
sc.pl.umap(
    bone_marrow_adata,
    color=["leiden"],
    size=8,
)

sc.pl.umap(
    bone_marrow_adata,
    color=["leiden"],
    # increase horizontal space between panels
    wspace=0.5,
    size=3,
    ncols = 1
)

# Doublet
sc.pl.umap(
    bone_marrow_adata,
    color=["predicted_doublet"],
    # increase horizontal space between panels
    wspace=0.5,
    size=3,
    ncols = 1
)

# UMAP of Doublet
sc.pl.umap(
    bone_marrow_adata,
    color=[ "doublet_score"],
    # increase horizontal space between panels
    wspace=0.5,
    size=3,
    ncols = 1
)

sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2, key_added="leiden_res0_02", resolution=0.02)
sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2, key_added="leiden_res0_5", resolution=0.5)
sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2, key_added="leiden_res2", resolution=2)

# Clustering at resolutions of 0.02, 0.5, and 2
sc.pl.umap(
    bone_marrow_adata,
    color=["leiden_res0_02", "leiden_res0_5", "leiden_res2"],
)

sc.pl.umap(
    bone_marrow_adata,
    color=["leiden_res0_02", "leiden_res0_5", "leiden_res2"],
    legend_loc="on data"
)

"""Cell Type Annotation"""

import pandas as pd
import celltypist as ct
import decoupler as dc

!wget wget -O result.txt 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "CSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Attribute name = "ensembl_gene_id" /><Attribute name = "external_gene_name" /></Dataset></Query>'
#this downloads the table of genes directly from ensemble

ensembl_var = pd.read_csv('result.txt', header = None)

ensembl_var.columns = ['ensembl_gene_id', 'gene_name']

ensembl_var.head()

# Query Omnipath and get PanglaoDB
markers = dc.op.resource(name="PanglaoDB", organism="human")

# Keep canonical cell type markers alone
markers = markers[markers["canonical_marker"]]

# Remove duplicated entries
markers = markers[~markers.duplicated(["cell_type", "genesymbol"])]

#Format because dc only accepts cell_type and genesymbol
markers = markers.rename(columns={"cell_type": "source", "genesymbol": "target"})
markers = markers[["source", "target"]]
markers.head()

#correct target to ensemble
markers = markers.merge(ensembl_var, left_on="target", right_on="gene_name", how="left")
markers = markers.drop(columns=["target"])
# Remove duplicated entries
markers = markers[~markers.duplicated(["source", "ensembl_gene_id"])]

#Format because dc only accepts cell_type and genesymbol
markers = markers.rename(columns={"source": "source", "ensembl_gene_id": "target"})

markers = markers[["source", "target"]]
markers = markers.dropna()

markers.head()

dc.mt.ulm(data=bone_marrow_adata, net=markers, tmin=3)

bone_marrow_adata.obsm["score_ulm"]

score = dc.pp.get_obsm(bone_marrow_adata, key="score_ulm")
score

bone_marrow_adata.obsm["score_ulm"].columns

# Natural Killer cells
sc.pl.umap(score,  color=["NK cells", "leiden_res2"], cmap="RdBu_r")

import seaborn as sns

sc.pl.violin(score, keys=["NK cells"], groupby="leiden_res0_02", rotation=90)

bone_marrow_adata_rank = dc.tl.rankby_group(score, groupby="leiden_res0_5", reference="rest", method="t-test_overestim_var")
bone_marrow_adata_rank = bone_marrow_adata_rank[bone_marrow_adata_rank["stat"] > 0]
bone_marrow_adata_rank

# Cluster Annotation
cluster_annotations = bone_marrow_adata_rank[bone_marrow_adata_rank["stat"] > 0].groupby("group").head(1).set_index("group")["name"].to_dict()

cluster_annotations

bone_marrow_adata.obs['cell_type'] = bone_marrow_adata.obs['leiden_res0_5'].map(cluster_annotations)

sc.pl.umap(bone_marrow_adata, color='cell_type', legend_loc='on data', title='Cell Type Annotation')

# Example of how to subset for multiple genes in the 'source' column
available_genes = set(bone_marrow_adata.var_names)

b_cell_markers = markers[markers['source'].isin(['B cells naive'])]['target']
b_cell_markers = b_cell_markers[b_cell_markers.isin(available_genes)]

t_cell_markers = markers[markers['source'].isin(['T cells'])]['target']
t_cell_markers = t_cell_markers[t_cell_markers.isin(available_genes)]

plasma_cells_markers = markers[markers['source'].isin(['Plasma cells'])]['target']
plasma_cells_markers = plasma_cells_markers[plasma_cells_markers.isin(available_genes)]

platelets_markers = markers[markers['source'].isin(['Platelets'])]['target']
platelets_markers = platelets_markers[platelets_markers.isin(available_genes)]

marker_genes_dict = {
    "T cell": t_cell_markers.head().tolist(),
    "B cells naive": b_cell_markers.head().tolist(),
    "Platelets": platelets_markers.head().tolist(),
    "Plasma cells": plasma_cells_markers.head().tolist(),
}

# Generate the dot plot
sc.pl.dotplot(
    bone_marrow_adata,
    var_names=marker_genes_dict, # Use the dictionary for grouped genes
    groupby='leiden', # Or whatever column holds your cell clusters (e.g., 'clusters', 'cell_type')
    dendrogram=True, # Set to True if you want to cluster the genes/groups
    color_map='Reds',
    use_raw=False
)

sc.tl.dendrogram(bone_marrow_adata, groupby='cell_type')
sc.pl.dotplot(bone_marrow_adata, marker_genes_dict, "cell_type", dendrogram=True)

sc.pl.stacked_violin(
    bone_marrow_adata, marker_genes_dict, groupby="leiden_res0_5",  dendrogram=True
)

sc.pl.heatmap(
    bone_marrow_adata, marker_genes_dict, groupby="leiden_res0_02", cmap="viridis", dendrogram=True
)

# Using genome tracks
sc.pl.tracksplot(bone_marrow_adata, marker_genes_dict, groupby="leiden_res0_02", dendrogram=False)

"""A.  What cell types did you identify?

 1. Neutrophils
 2. Plasma Cells
 3. Plaletes
 4. B cells Naive
 5. T cells
 6. Dendritic cells
 7. Gamma delta T cells



B. Explain the biological role of each cell type in Bone Marrow or peripheral immunity

1. Neutrophils: active phagocytes that release enzymes to eliminate bacteria

2. Plasma cells: differentiated B-lymophocytes which secretes immunoglobin or antibodies

3. Plaletes: discoid, anuecleate cells that help in clot blood

4. B cells naive:key regulating cells, responsible for antibody-mediated immunity

5. T cells: responsible for cell-mediated immunity

6. Dendritic cells:acquisition of antigens and stimulation of lymphocytes

7. Gamma delta T cell: bridges the innate and adaptive immune response

C. Is the tissue source really bone marrow? Justify your answer
Your job is to reason your way toward (or away from) that conclusion using:

Expected vs. missing lineage populations:
Erythroid Lineage
Megakaryocytic lineage
Hematopoietic stem and progenitor cells
Myeloic cells

Observed populations: T cells, B cells, Neutrophils, Dendritic cells, Plasma cells and Platelets.

Typical frequency distributions: Presence of Lymphocyte (T cells, B cells naive, Gamma delta T cells), Dendritic cells, Neutrophil, Moderate plasma cells, and low platelets.

Presence or absence of progenitors: There is absence of CD34+ progenitors, megakaryocytes, eythroid and endothelial cell, all of which are seen in bone marrow cells.

Conclusion: The dataset is not bone marrow but peripheral blood mononuclear cells (PBMC).
Based on the absence of hallmark bone-marrow lineages (erythroid and megakaryocytic cells), the lack of detectable hematopoietic stem/progenitor (CD34+/KIT+) signatures, and a cell composition dominated by mature lymphocytes (T/B/NK) plus expected PBMC contaminants (dendritic cells, neutrophil fragments, plasma cells, platelets), the most parsimonious and testable conclusion is that this dataset represents PBMC / a PBMC-like preparation, not an unsorted bone-marrow sample.

D. Based on the relative abundance of cell types, is the patient healthy or infected?

Neutrophils: Neutrophil is present but only a small fraction.

monocytes: No annotated monocyte clusters, however dendritic cell is present, which point to antigen activation.

NK cell activation states: No annotated NK cells, but gamma delta T cells are annotated and are moderately abundant

Lymphocyte depletion or expansion: Lymphocyte is expanded due to the relative abundance of the T cells and B cell cluster.

Conclusion: The patient present an active infection.   
Justification: Abundant plasma cells cluster, which indicate active infection. The t cells, b cells and gamma delta T cells are expanded but neutrophils are not, no monocyte cluster and presence of dendritic cells.
"""