# -*- coding: utf-8 -*-
"""Single cell RNA sequencing- HackBio Stage Two

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntZ0rkGtKN57eOzHXYFhzuhaAMhk_7K7

HackBio Stage Two

Reproduce a single-cell analysis pipleine using Scanpy and Anndata
Dataset is BoneMarrow.h5ad.

INSTALLATION OF LIBRARIES:
Scanpy
Anndata
igraph
Celltypist
Decoupler
"""

# Installation of Libraries
!pip install scanpy
!pip install anndata
!pip install igraph
!pip install celltypist
!pip install decoupler

# import core tools
import scanpy as sc
import anndata as ad

# Load raw data
!wget https://media.githubusercontent.com/media/josoga2/sc/refs/heads/main/bone_marrow.h5ad

# The dataset is loaded into an Anndata object
# This structure stores gene expression, metadata and embeddings
bone_marrow_adata = sc.read_h5ad('bone_marrow.h5ad')

print(bone_marrow_adata)

bone_marrow_adata.shape

bone_marrow_adata.var.head()

bone_marrow_adata.obs.head()

# Assign to DataFrame
bone_marrow_adata.to_df()

"""QUALITY CONTROL: To keep high quality cells and informative genes"""

# Basic Quality Control Filtering
# Cells expressing too few genes are likely empty droplets
bone_marrow_adata.var_names_make_unique()
bone_marrow_adata.obs_names_make_unique()

bone_marrow_adata.var['MT'] = bone_marrow_adata.var['feature_name'].str.startswith('MT-')
bone_marrow_adata.var['RIBO'] = bone_marrow_adata.var['feature_name'].str.startswith(('RPS', 'RPL'))
bone_marrow_adata.var['HB'] = bone_marrow_adata.var['feature_name'].str.contains('^HB[^(P)]')

mt_genes = bone_marrow_adata.var[bone_marrow_adata.var['MT']]
mt_genes

sc.pp.calculate_qc_metrics(
bone_marrow_adata, qc_vars=["MT", 'RIBO', 'HB'], inplace=True, log1p=True)

bone_marrow_adata.obs.head()

bone_marrow_adata.var.head()

# number of genes in cells
sc.pl.violin(
    bone_marrow_adata,
    ["n_genes_by_counts"],
    jitter=0.4,
    multi_panel=False,
)

# Total counts of genes
sc.pl.violin(
    bone_marrow_adata,
    ["total_counts"],
    jitter=0.4,
    multi_panel=False,
)

# Mitochondrial genes
sc.pl.violin(
    bone_marrow_adata,
    ["pct_counts_MT"],
    jitter=0.4,
    multi_panel=False,
)

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_HB")

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_RIBO")

bone_marrow_adata = bone_marrow_adata[
    bone_marrow_adata.obs['pct_counts_RIBO'] < 10]

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color = "pct_counts_RIBO")

sc.pl.scatter(bone_marrow_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

sc.pp.scrublet(bone_marrow_adata) #doublet detection

"""NORMALIZATION"""

# Normalize counts so each cell has equivalent total expression
bone_marrow_adata.layers["counts"] = bone_marrow_adata.X.copy()

# Normalizing to median total counts
sc.pp.normalize_total(bone_marrow_adata)
# Logarithmize the data
sc.pp.log1p(bone_marrow_adata)

# Highly variable genes
# HVGs retain biologically informative genes
sc.pp.highly_variable_genes(bone_marrow_adata, n_top_genes=1000)

sc.pl.highly_variable_genes(bone_marrow_adata )

"""Dimensionality Reduction: Principal Component Analysis, UMAP. Non Linear Dimensionality Reduction: Leiden"""

# Principal Component Analysis
sc.tl.pca(bone_marrow_adata)

sc.pl.pca_variance_ratio(bone_marrow_adata, n_pcs=10, log=False)

# Neighbor Graph and Clustering
sc.pp.neighbors(bone_marrow_adata)

sc.tl.umap(bone_marrow_adata)

sc.pl.pca(
    bone_marrow_adata,
    color=["pct_counts_MT"]
)

sc.pl.pca(
    bone_marrow_adata,
    color=["pct_counts_HB"]
)

# UMAP Visualization
sc.tl.umap(bone_marrow_adata)

sc.pl.umap(
    bone_marrow_adata,
    color=["pct_counts_RIBO"],
    size=8,
)

sc.pl.umap(
    bone_marrow_adata,
    color=["pct_counts_HB"],
    size=8,
)

sc.pl.umap(
    bone_marrow_adata,
    color=["pct_counts_MT"],
    size=8,
)

sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2)

# Leiden Clustering: detects communities representing cell types
sc.pl.umap(
    bone_marrow_adata,
    color=["leiden"],
    size=8,
)

sc.pl.umap(
    bone_marrow_adata,
    color=["leiden"],
    # increase horizontal space between panels
    wspace=0.5,
    size=3,
    ncols = 1
)

# Doublet Visualization
sc.pl.umap(
    bone_marrow_adata,
    color=["predicted_doublet"],
    # increase horizontal space between panels
    wspace=0.5,
    size=3,
    ncols = 1
)

# UMAP of Doublet
sc.pl.umap(
    bone_marrow_adata,
    color=[ "doublet_score"],
    # increase horizontal space between panels
    wspace=0.5,
    size=3,
    ncols = 1
)

sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2, key_added="leiden_res0_02", resolution=0.02)
sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2, key_added="leiden_res0_5", resolution=0.5)
sc.tl.leiden(bone_marrow_adata, flavor="igraph", n_iterations=2, key_added="leiden_res2", resolution=2)

# Clustering at resolutions of 0.02, 0.5, and 2
sc.pl.umap(
    bone_marrow_adata,
    color=["leiden_res0_02", "leiden_res0_5", "leiden_res2"],
)

sc.pl.umap(
    bone_marrow_adata,
    color=["leiden_res0_02", "leiden_res0_5", "leiden_res2"],
    legend_loc="on data"
)

"""Cell Type Annotation"""

import pandas as pd
import celltypist as ct
import decoupler as dc

!wget wget -O result.txt 'http://www.ensembl.org/biomart/martservice?query=<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Query><Query  virtualSchemaName = "default" formatter = "CSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" ><Dataset name = "hsapiens_gene_ensembl" interface = "default" ><Attribute name = "ensembl_gene_id" /><Attribute name = "external_gene_name" /></Dataset></Query>'
#this downloads the table of genes directly from ensemble

ensembl_var = pd.read_csv('result.txt', header = None)

ensembl_var.columns = ['ensembl_gene_id', 'gene_name']

ensembl_var.head()

# Query Omnipath and get PanglaoDB
markers = dc.op.resource(name="PanglaoDB", organism="human")

# Keep canonical cell type markers alone
markers = markers[markers["canonical_marker"]]

# Remove duplicated entries
markers = markers[~markers.duplicated(["cell_type", "genesymbol"])]

#Format because dc only accepts cell_type and genesymbol
markers = markers.rename(columns={"cell_type": "source", "genesymbol": "target"})
markers = markers[["source", "target"]]
markers.head()

#correct target to ensemble
markers = markers.merge(ensembl_var, left_on="target", right_on="gene_name", how="left")
markers = markers.drop(columns=["target"])
# Remove duplicated entries
markers = markers[~markers.duplicated(["source", "ensembl_gene_id"])]

#Format because dc only accepts cell_type and genesymbol
markers = markers.rename(columns={"source": "source", "ensembl_gene_id": "target"})

markers = markers[["source", "target"]]
markers = markers.dropna()

markers.head()

dc.mt.ulm(data=bone_marrow_adata, net=markers, tmin=3)

bone_marrow_adata.obsm["score_ulm"]

score = dc.pp.get_obsm(bone_marrow_adata, key="score_ulm")
score

bone_marrow_adata.obsm["score_ulm"].columns

# Natural Killer cells
sc.pl.umap(score,  color=["NK cells", "leiden_res2"], cmap="RdBu_r")

import seaborn as sns

sc.pl.violin(score, keys=["NK cells"], groupby="leiden_res0_02", rotation=90)

bone_marrow_adata_rank = dc.tl.rankby_group(score, groupby="leiden_res0_5", reference="rest", method="t-test_overestim_var")
bone_marrow_adata_rank = bone_marrow_adata_rank[bone_marrow_adata_rank["stat"] > 0]
bone_marrow_adata_rank

# Cluster Annotation
cluster_annotations = bone_marrow_adata_rank[bone_marrow_adata_rank["stat"] > 0].groupby("group").head(1).set_index("group")["name"].to_dict()

cluster_annotations

bone_marrow_adata.obs['cell_type'] = bone_marrow_adata.obs['leiden_res0_5'].map(cluster_annotations)

sc.pl.umap(bone_marrow_adata, color='cell_type', legend_loc='on data', title='Cell Type Annotation')

# Example of how to subset for multiple genes in the 'source' column
# Ensure available_genes contains Ensembl IDs as they are used in adata.var_names
# Fix: Use bone_marrow_adata.var_names which contains the unique-ified gene symbols
available_genes = set(bone_marrow_adata.var_names)

NK_cells_markers = markers[markers['source'].isin(['NK cells'])]['target']
NK_cells_markers = NK_cells_markers[NK_cells_markers.isin(available_genes)]

T_cells_markers = markers[markers['source'].isin(['T cells'])]['target']
T_cells_markers = T_cells_markers[T_cells_markers.isin(available_genes)]

Plasma_cells_markers = markers[markers['source'].isin(['Plasma cells'])]['target']
Plasma_cells_markers = Plasma_cells_markers[Plasma_cells_markers.isin(available_genes)]

Platelets_markers = markers[markers['source'].isin(['Platelets'])]['target']
Platelets_markers = Platelets_markers[Platelets_markers.isin(available_genes)]

Nuocytes_markers = markers[markers['source'].isin(['Nuocytes'])]['target']
Nuocytes_markers = Nuocytes_markers[Nuocytes_markers.isin(available_genes)]

Neutrophil_markers = markers[markers['source'].isin(['Neutrophils'])]['target']
Neutrophil_markers = Neutrophil_markers[Neutrophil_markers.isin(available_genes)]

Monocytes_markers = markers[markers['source'].isin(['Monocytes'])]['target']
Monocytes_markers = Monocytes_markers[Monocytes_markers.isin(available_genes)]

display(Neutrophil_markers)

marker_genes_dict = {
    "T cells": T_cells_markers.head().tolist(),
    "Nuocytes": Nuocytes_markers.head().tolist(),
    "Neutrophils": Neutrophil_markers.head().tolist(),
    "Monocytes": Monocytes_markers.head().tolist(),
    "Platelets": Platelets_markers.head().tolist(),
    "Plasma cells": Plasma_cells_markers.head().tolist(),
    "NK cells": NK_cells_markers.head().tolist(),
    }

# Generate the dot plot
sc.pl.dotplot(
    bone_marrow_adata,
    var_names=marker_genes_dict, # Use the dictionary for grouped genes
    groupby='leiden', # Or whatever column holds your cell clusters (e.g., 'clusters', 'cell_type')
    dendrogram=True, # Set to True if you want to cluster the genes/groups
    color_map='Reds',
    use_raw=False,
)

sc.tl.dendrogram(bone_marrow_adata, groupby='cell_type')
sc.pl.dotplot(bone_marrow_adata, marker_genes_dict, "cell_type", dendrogram=True)

sc.pl.stacked_violin(
    bone_marrow_adata, marker_genes_dict, groupby="leiden_res0_5",  dendrogram=True
)

sc.pl.heatmap(
    bone_marrow_adata, marker_genes_dict, groupby="leiden_res0_02", cmap="viridis", dendrogram=True
)

# Using genome tracks
sc.pl.tracksplot(bone_marrow_adata, marker_genes_dict, groupby="leiden_res0_02", dendrogram=False)

"""A.  CELL TYPE IDENTIFICATION:
 Dominant Populations:
 1. Neutrophils
 2. Plasma Cells
 3. Plaletes
 4. Nuocytes
 5. T cells
 6. Monocytes
 7. Nk cells

Missing Populations: Erythoid Lineage, Megakaryocyte- erythoid progenitors, myeloid progenitors.
Interpretation: Mature immune cell landscape consistent with peripheral blood

B. Biological Role of Each Cell Type:

1. Neutrophils: active phagocytes that release enzymes to eliminate bacteria

2. Plasma cells: differentiated B-lymophocytes which secretes immunoglobin or antibodies

3. Plaletes: discoid, anuecleate cells that help in clot blood

4. Nuocytes: also known as type-2 innate lymphoid cells. They provide first line of defense against pathogens

5. T cells: responsible for cell-mediated immunity

6. Monocytes: innate immune cells that sere as key defenders and regulators in the immune system

7. Nk cells: rapid response cytotoxic lymphocytes that detect and eliminate abnormal cells

C. Tissue Origin Conclusion: Peripheral Blood Mononuclear Cell not Bone Marrow
Justification: Based on the absence of hallmark bone-marrow lineages (erythroid and megakaryocytic cells), the lack of detectable hematopoietic stem/progenitor (CD34+/KIT+) signatures, and a cell composition dominated by mature lymphocytes (T/B/NK) plus expected PBMC contaminants (dendritic cells, neutrophil fragments, plasma cells, platelets), this dataset represents PBMC / a PBMC-like preparation, not an unsorted bone-marrow sample.

According to Smith et al, 2025: Bone marrow functions as the central site of hematopoiesis, housing hematopoietic stem cells, lineage-committed progenitors, erythroid precursors, and megakaryocyte developmental stages. This environment also contains stromal cells, adipocytes, and a rich network of supportive niche cells, making bone marrow inherently heterogeneous and dominated by immature or differentiating cell types.
In contrast, peripheral blood contains only fully differentiated immune cells that have exited the bone marrow after maturation. Peripheral blood therefore lacks erythroid progenitors, megakaryocyte precursors, and early myeloid intermediates. Instead, it is populated by mature T cells, neutrophils, monocytes, NK cells, plasma cells, and circulating platelets. When these well-established differences are applied to the present dataset, the conclusion becomes unambiguous. The sample shows only mature immune cells—T cells, B cells, neutrophils, dendritic cells, monocytes, plasma cells, and platelets—and completely lacks hallmarks of bone marrow such as erythroid precursors, megakaryocyte lineage cells, hematopoietic stem cells, or immature granulocyte populations.
Therefore, this profile aligns with the immunological characteristics of peripheral blood, particularly under inflammatory conditions, and is incompatible with the composite, progenitor-rich architecture of bone marrow described in the paper. This dataset represents peripheral blood rather than bone marrow.

D. Based on the relative abundance of cell types, is the patient healthy or infected?

Neutrophils: Marked neutrophil expansion, which indicates hallmark of acute bacterial type inflammation. The neutrophil are first responders triggered by IL-8/G-CSF in infection. A large neutrophil cluster means the innate immune system is actively responding to pathogen-associated signals.
are
Monocytes:  Monocytes are also expanded and are involved in myeloid-driven inflammatory response. The monocyte compartment is also large, supporting the neutrophil signal, where emergency myelopoiesis is triggered.

NK cell activation states: Nk cells are present but appear moderate, which argues against a primarly viral progress.

Lymphocyte depletion or expansion: Lymphocyte expansion here is evident in plasma cells (B cell response) and stable T cell proportion, supporting an ongoing adaptive response to a pathogen.

Conclusion: The immune landscape shows meutrophils and monocytes expansin which indicates recruitment of phagocytes for pathogen clearance. Also, there is presence of both innate and adaptive immune response which signals an active infection.  The patient present an active infection.
"""